import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "../globals.css";
<<<<<<< HEAD
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster";



const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
=======

import { Toaster } from "@/components/ui/toaster";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";

const epilogue = Epilogue({ subsets: ["latin"] });



export default async function RootLayout({
>>>>>>> 8ae46e8b9ad5478c2bff3e0076ee1faccc18c0aa
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  return (
    <html lang="en">
      <body className={`${epilogue.className} relative overflow-x-hidden`}>
    
        <main className="grid grid-cols-2">
          <div className="relative h-screen">
            <div className="absolute w-full h-full">
              <Image src="/images/bg-auth.png" alt="/images/bg-auth.png" fill objectFit="cover" objectPosition="top"/>
            </div>
          </div>
          <div className="w-full relative">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
            {children}
            </div>
          </div>
        
        </main>
    <Toaster />
=======
  const session = await getServerSession(authOptions)

  if(session !== null) {
    return redirect('/');
  }
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main>
          {children}
          <Toaster />
        </main>
>>>>>>> 8ae46e8b9ad5478c2bff3e0076ee1faccc18c0aa
      </body>
    </html>
  );
}
